patchesStrategicMerge:
- traefik-ingress-controller-deployment.yaml
- traefik-ingress-controller-service.yaml
- cybercrime-api-ingress.yaml
- arango-claim.yaml
- cybercrime-frontend-ingress.yaml
- minio-deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certs-claim.yaml
- azure-storageclass.yaml
- arango-secrets.yaml
- cybercrime-api-secrets.yaml
- minio-secrets.yaml
- flux.yaml
- ../../base
images:
- name: acrrcmpcybercrime.azurecr.io/api
  newTag: master-f70131ecac0629b21b5ffbcf20fdff0d4fe1f3e6
- name: acrrcmpcybercrime.azurecr.io/frontend
  newTag: master-d6a30426fd7bb1db1618890d86ebd8ec44c5acda
- name: traefik
  newTag: "1.7"
