patchesStrategicMerge:
- traefik-ingress-controller-deployment.yaml
- traefik-ingress-controller-service.yaml
- cybercrime-api-ingress.yaml
- arango-claim.yaml
- cybercrime-frontend-ingress.yaml
- minio-deployment.yaml
- cybercrime-frontend-deployment.yaml
- cybercrime-api-deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certs-claim.yaml
- azure-storageclass.yaml
- arango-secrets.yaml
- cybercrime-api-secrets.yaml
- minio-secrets.yaml
- flux.yaml
- sealed-secrets-controller-deployment.yaml
- sealed-secrets-crd.yaml
- ../../base
images:
- name: acrrcmpcybercrime.azurecr.io/api
  newTag: master-27336d3a24d64b33bb9a040dee60acf56df26379
- name: acrrcmpcybercrime.azurecr.io/frontend
  newTag: master-42f71f7d5722ee3f5361cb438e38a6238dfde396
- name: traefik
  newTag: "1.7"
